export const CARGAR_CHATS = "CARGAR_CHATS";
export const CARGAR_CHATS_ERROR = "CARGAR_CHATS_ERROR";
export const INSERTAR_CHAT = "INSERTAR_CHAT";
export const INSERTAR_CHAT_ERROR = "INSERTAR_CHAT_ERROR";
export const SETEAR_CHAT_ACTUAL="SETEAR_CHAT_ACTUAL";